# Generated by Django 2.0.9 on 2018-12-04 06:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_reporter_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter_list',
            name='name',
        ),
        migrations.AddField(
            model_name='reporter_list',
            name='lead_detail',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='crm_app.User_Lead_List'),
            preserve_default=False,
        ),
    ]
