# Generated by Django 2.0.9 on 2018-12-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_auto_20181204_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter_list',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
