# Generated by Django 2.0.9 on 2018-12-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_remove_reporter_list_lead_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter_list',
            name='user_detail',
        ),
        migrations.DeleteModel(
            name='Reporter_List',
        ),
    ]
