# Generated by Django 2.0.9 on 2018-12-04 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_app', '0007_auto_20181204_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='reporter_list',
            name='report_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporters_list', to='crm_app.User_Details'),
        ),
        migrations.AddField(
            model_name='reporter_list',
            name='reporter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.User_Details'),
        ),
        migrations.AddField(
            model_name='lead_data',
            name='user_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_list', to='crm_app.User_Details'),
        ),
    ]
