# Generated by Django 2.0.9 on 2018-12-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0013_auto_20181204_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter_list',
            name='report_to',
        ),
        migrations.RemoveField(
            model_name='reporter_list',
            name='reporter_id',
        ),
        migrations.DeleteModel(
            name='Reporter_List',
        ),
    ]
