# Generated by Django 2.0.9 on 2018-12-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0017_auto_20181208_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_list',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
