# Generated by Django 2.0.9 on 2018-12-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0018_auto_20181208_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='followed_history',
            name='status',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
