# Generated by Django 2.0.9 on 2018-12-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0019_followed_history_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='followed_history',
            name='reason',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
