# Generated by Django 2.0.9 on 2018-12-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0022_auto_20181211_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead_data',
            name='user_detail',
        ),
        migrations.DeleteModel(
            name='Lead_Data',
        ),
    ]
