# Generated by Django 2.0.9 on 2018-12-12 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0024_auto_20181212_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followed_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=100)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_history', to='crm_app.Lead_List')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follwup_list', to='crm_app.User_Details')),
            ],
        ),
    ]
