# Generated by Django 2.0.9 on 2018-12-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0026_auto_20181212_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_list',
            name='nxt_flw_dt',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
