# Generated by Django 2.0.9 on 2018-12-13 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0027_auto_20181212_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amt', models.CharField(max_length=10)),
                ('invc_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='lead_list',
            name='brnch_loc',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lead_list',
            name='campaign',
            field=models.CharField(default='online website', max_length=30),
        ),
        migrations.AddField(
            model_name='lead_list',
            name='created_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lead_list',
            name='degree',
            field=models.CharField(default='B.E', max_length=100),
        ),
        migrations.AddField(
            model_name='lead_list',
            name='enquired_for',
            field=models.CharField(default='Internship', max_length=200),
        ),
        migrations.AddField(
            model_name='lead_list',
            name='marks',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='lead_list',
            name='tchngly_lk_fr',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='lead_list',
            name='yop',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice_list',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_invoice_list', to='crm_app.Lead_List'),
        ),
        migrations.AddField(
            model_name='invoice_list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invoice_list', to='crm_app.User_Details'),
        ),
    ]
