# Generated by Django 2.0.9 on 2018-12-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0029_invoice_list_invc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_list',
            name='invc_id',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
