# Generated by Django 2.0.9 on 2018-12-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0034_invoice_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_list',
            name='invc_id',
        ),
    ]
