# Generated by Django 2.0.9 on 2018-12-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0035_remove_invoice_list_invc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_list',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='invoice_list',
            name='user',
        ),
        migrations.DeleteModel(
            name='Invoice_List',
        ),
    ]
