# Generated by Django 2.0.9 on 2018-12-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0037_invoice_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_list',
            name='nxt_flw_dt',
            field=models.DateTimeField(blank=True),
        ),
    ]
