# Generated by Django 2.0.9 on 2018-12-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0038_auto_20181220_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=40)),
            ],
        ),
    ]
