# Generated by Django 2.0.9 on 2018-12-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0039_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
