# Generated by Django 2.0.9 on 2018-12-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0040_auto_20181222_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=40)),
                ('taxable_fees', models.CharField(max_length=10)),
                ('non_txbl_fees', models.CharField(max_length=10)),
            ],
        ),
    ]
