# Generated by Django 2.0.9 on 2018-12-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0041_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brnch_name', models.CharField(max_length=30)),
            ],
        ),
    ]
