# Generated by Django 2.0.9 on 2018-12-26 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0042_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_list',
            name='course',
            field=models.ForeignKey(default='BLR', on_delete=django.db.models.deletion.CASCADE, related_name='course_inc', to='crm_app.Courses'),
            preserve_default=False,
        ),
    ]
