# Generated by Django 2.0.9 on 2018-12-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0043_invoice_list_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_list',
            name='course',
        ),
    ]
