# Generated by Django 2.0.9 on 2018-12-26 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0044_remove_invoice_list_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_list',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_inc', to='crm_app.Courses'),
            preserve_default=False,
        ),
    ]
