# Generated by Django 2.0.9 on 2018-12-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0046_auto_20181231_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followed_history',
            name='date',
        ),
    ]
