# Generated by Django 2.0.9 on 2018-12-31 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0047_remove_followed_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='followed_history',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
