# Generated by Django 2.0.9 on 2019-01-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0049_bills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='paid_date',
        ),
    ]
