# Generated by Django 2.0.9 on 2019-01-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0050_auto_20190103_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bills',
        ),
    ]
