# Generated by Django 2.0.9 on 2019-01-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0055_auto_20190103_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='bill_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
