# Generated by Django 2.0.9 on 2019-01-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0056_auto_20190103_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='bill_id',
        ),
    ]
