# Generated by Django 2.0.9 on 2019-01-04 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0058_bills_bill_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=50)),
                ('paid_date', models.DateTimeField(auto_now=True)),
                ('bill_id', models.CharField(default='', max_length=100)),
                ('payment_type', models.CharField(max_length=40)),
                ('dated', models.DateField()),
                ('drawn_on', models.DateField()),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invc_bills', to='crm_app.Invoice_List')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_billed', to='crm_app.User_Details')),
            ],
        ),
        migrations.RemoveField(
            model_name='bills',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bills',
        ),
    ]
