# Generated by Django 2.0.9 on 2019-01-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0060_installments'),
    ]

    operations = [
        migrations.AddField(
            model_name='installments',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
