# Generated by Django 2.0.9 on 2019-01-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0061_installments_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='dated',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='drawn_on',
            field=models.DateField(blank=True),
        ),
    ]
